"""Create Provider and ServiceArea tables

Revision ID: a01a32c1b25b
Revises:
Create Date: 2024-09-26 21:33:26.361017

"""
import geoalchemy2
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models import Provider, ServiceArea


# revision identifiers, used by Alembic.
revision: str = 'a01a32c1b25b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_table('service_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('geojson', geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.CheckConstraint('price > 0', name='check_positive_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_service_areas_geojson', table_name='service_areas', postgresql_using='gist')
    op.create_index('idx_service_areas_geojson', 'service_areas', ['geojson'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_service_areas_id'), 'service_areas', ['id'], unique=False)
    op.create_index(op.f('ix_service_areas_name'), 'service_areas', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_areas_name'), table_name='service_areas')
    op.drop_index(op.f('ix_service_areas_id'), table_name='service_areas')
    op.drop_index('idx_service_areas_geojson', table_name='service_areas', postgresql_using='gist')
    op.drop_table('service_areas')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
